apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-ch
---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-NUM
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helloworld-channel
  namespace: helloworld-ch
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/application-samples.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: helloworld-app-placement
  namespace: helloworld-NUM
  labels:
    app: helloworld-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: MANAGED-CLUSTER-NAME
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helloworld-app-subscription-NUM
  namespace: helloworld-NUM
  labels:
    app: helloworld-app-NUM
  annotations:
    apps.open-cluster-management.io/github-path: helloworld
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: helloworld-ch/helloworld-channel
  placement:
    placementRef:
      name: helloworld-app-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: helloworld-NUM
  namespace: helloworld-NUM
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helloworld-app-NUM
