apiVersion: v1
kind: Namespace
metadata:
  name: ns-ch
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-sub-NUM
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: predev-ch
  namespace: ns-ch
  labels:
    app: nginx-app-details
spec:
  type: HelmRepo
  pathname: https://charts.helm.sh/stable/
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: ns-sub-NUM
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: MANAGED-CLUSTER-NAME
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-NUM
  namespace: ns-sub-NUM
  labels:
    app: nginx-app-details-NUM
spec:
  channel: ns-ch/predev-ch
  name: nginx-ingress
  packageFilter:
    version: "1.36.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: nginx-app-details-NUM
  name: nginx-app-NUM
  namespace: ns-sub-NUM
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: nginx-app-details-NUM